# Generated by Django 3.1.7 on 2021-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20210305_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sumrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='countrate',
            field=models.IntegerField(default=0),
        ),
    ]
